# Generated by Django 4.1 on 2022-08-18 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('ter', 'Termogênico'), ('wey', 'WheyProtein'), ('col', 'Colágeno'), ('alb', 'Albumina'), ('car', 'Carnitina'), ('mvit', 'Multivitamínico'), ('bcaa', 'BCAA'), ('glu', 'Glutamina'), ('cre', 'Creatina'), ('arg', 'Arginina'), ('Hip', 'Hipercalórico')], max_length=4)),
                ('tipo', models.CharField(choices=[('hip', 'Hipercalórico'), ('ter', 'Termogênico'), ('pro', 'Proteico'), ('antx', 'Antioxidante'), ('horm', 'Hormonal'), ('vit', 'Polivitamínico'), ('pbc', 'Probiótico'), ('amn', 'Aminoácido')], max_length=4)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem', models.ImageField(blank=True, max_length=250, null=True, upload_to='suplementos/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplements.marca')),
            ],
        ),
    ]
