# Generated by Django 4.1 on 2022-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplemento',
            name='tipo',
            field=models.CharField(choices=[('cab', 'Carboidratos'), ('ter', 'Termogênico'), ('pro', 'Proteico'), ('antx', 'Antioxidante'), ('horm', 'Hormonal'), ('vit', 'Polivitamínico'), ('pbc', 'Probiótico'), ('amn', 'Aminoácido')], max_length=4),
        ),
    ]
